"""add_ondelete_cascade_and_set_null_to_all_fks

Revision ID: dae40facebe3
Revises: a1b2c3d4e5f6
Create Date: 2026-06-23 11:16:59.543486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dae40facebe3'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'file_type',
               existing_type=postgresql.ENUM('mp3', 'wav', 'm4a', 'ogg', 'pdf', 'docx', 'txt', name='meetingfiletype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('meetings', 'status',
               existing_type=postgresql.ENUM('uploaded', 'transcribing', 'transcribed', 'processing', 'completed', 'failed', name='meetingstatus'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('meetings', 'uploaded_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('meetings_project_id_fkey'), 'meetings', type_='foreignkey')
    op.drop_constraint(op.f('meetings_team_id_fkey'), 'meetings', type_='foreignkey')
    op.drop_constraint(op.f('meetings_uploaded_by_fkey'), 'meetings', type_='foreignkey')
    op.create_foreign_key(None, 'meetings', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'meetings', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'meetings', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.alter_column('projects', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('projects', 'ai_difficulty',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('projects', 'ai_analysis_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.drop_constraint(op.f('projects_created_by_fkey'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('projects_team_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'projects', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'critical', name='taskpriority'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('pending', 'in_progress', 'completed', name='taskstatus'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint(op.f('tasks_assignee_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    op.alter_column('team_members', 'role_in_team',
               existing_type=postgresql.ENUM('team_lead', 'team_member', name='memberrole'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('teams', 'manager_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('teams_manager_id_fkey'), 'teams', type_='foreignkey')
    op.drop_constraint(op.f('teams_project_id_fkey'), 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'users', ['manager_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'teams', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('manager', 'team_lead', 'team_member', name='userrole'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('manager', 'team_lead', 'team_member', name='userrole'),
               existing_nullable=False)
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key(op.f('teams_project_id_fkey'), 'teams', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('teams_manager_id_fkey'), 'teams', 'users', ['manager_id'], ['id'])
    op.alter_column('teams', 'manager_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('team_members', 'role_in_team',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('team_lead', 'team_member', name='memberrole'),
               existing_nullable=False)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_assignee_id_fkey'), 'tasks', 'users', ['assignee_id'], ['id'])
    op.alter_column('tasks', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('pending', 'in_progress', 'completed', name='taskstatus'),
               existing_nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('low', 'medium', 'high', 'critical', name='taskpriority'),
               existing_nullable=False)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_team_id_fkey'), 'projects', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(op.f('projects_created_by_fkey'), 'projects', 'users', ['created_by'], ['id'])
    op.alter_column('projects', 'ai_analysis_status',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'ai_difficulty',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.create_foreign_key(op.f('meetings_uploaded_by_fkey'), 'meetings', 'users', ['uploaded_by'], ['id'])
    op.create_foreign_key(op.f('meetings_team_id_fkey'), 'meetings', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(op.f('meetings_project_id_fkey'), 'meetings', 'projects', ['project_id'], ['id'])
    op.alter_column('meetings', 'uploaded_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('meetings', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('uploaded', 'transcribing', 'transcribed', 'processing', 'completed', 'failed', name='meetingstatus'),
               existing_nullable=False)
    op.alter_column('meetings', 'file_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('mp3', 'wav', 'm4a', 'ogg', 'pdf', 'docx', 'txt', name='meetingfiletype'),
               existing_nullable=False)
    # ### end Alembic commands ###
